export const LIGHT_MODE_BACKGROUND_LUMINANCE = 1;
export const DARK_MODE_BACKGROUND_LUMINANCE = 0.02;
export const DEFAULT_BORDER_TO_BACKGROUND_CONTRAST = 5;
export const BASE_COLOUR_LUMINANCE_LIGHT_MODE = 0.6;
export const BASE_COLOUR_LUMINANCE_DARK_MODE = 0.12;
export const INPUT_FIELD_TO_PAGE_CONTRAST = 1.2;
